name: Documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  document:
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: macos-latest
    
    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup pages
        uses: actions/configure-pages@v5
        
      - name: Build documentation
        run: |
          mkdir _site
          swift package \
            --allow-writing-to-directory _site \
            generate-documentation \
            --target XCResultOwnersCore \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path "xcresultowners" \
            --output-path _site
      
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
